services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama-network

  lab:
    build: .
    container_name: lab
    ports:
      - "8888:8888"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - UV_LINK_MODE=copy
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    networks:
      - ollama-network

volumes:
  ollama-models:
  gitlab-data:

networks:
  ollama-network:
    driver: bridge
